version: '3'

services:
  # ------------- db ------------- #
  redis:
    image: registry.cn-shanghai.aliyuncs.com/pathim/redis:latest-arm64
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true
    networks:
      pathim_dep_net:
        ipv4_address: 172.25.1.10
  cassandra:
    image: registry.cn-shanghai.aliyuncs.com/pathim/cassandra:4.0.0-arm64
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    ports:
#      - "7000:7000"
      - "9042:9042"
    restart: always
    privileged: true
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.98
      - CASSANDRA_SEEDS=192.168.1.98
      - CASSANDRA_CLUSTER_NAME=pathim
      - HEAP_NEWSIZE=512M
      - MAX_HEAP_SIZE=1024M
      - JVM_OPTS=-Xms1024M -Xmx1024M
    networks:
      pathim_dep_net:
        ipv4_address: 172.25.1.30

  # ============= db ============= #
  
  
  #jaeger链路追踪
  jaeger:
    image: registry.cn-shanghai.aliyuncs.com/pathim/jaeger-all-in-one:latest-arm64
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    networks:
      pathim_dep_net:
        ipv4_address: 172.25.2.1

  elasticsearch:
    image: registry.cn-shanghai.aliyuncs.com/pathim/elasticsearch:7.13.4-arm64
    user: root
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      pathim_dep_net:
        ipv4_address: 172.25.2.4


  #zookeeper是kafka的依赖
  zookeeper:
    image: registry.cn-shanghai.aliyuncs.com/pathim/zookeeper:3.7-arm64
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./data/zookeeper:/data
    ports:
      - "2181:2181"
    networks:
      pathim_dep_net:
        ipv4_address: 172.25.2.8

  #消息队列
  kafka:
    image: registry.cn-shanghai.aliyuncs.com/pathim/kafka:arm64v8-2.2.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://192.168.1.98:9092
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
    networks:
      pathim_dep_net:
        ipv4_address: 172.25.2.9
    depends_on:
      - zookeeper

  kafka-ui:
    image: registry.cn-shanghai.aliyuncs.com/pathim/kafka-ui:latest-arm64
    ports:
      - 8081:8080
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.1.98:9092
      - KAFKA_CLUSTERS_0_NAME=docker
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    restart: always
    networks:
      pathim_dep_net:
        ipv4_address: 172.25.2.10
    depends_on:
      - kafka
      - zookeeper

networks:
  pathim_dep_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16