Name: msggateway-ws
Host: 0.0.0.0
Port: 9090

Websocket:
  MaxConnNum: 10000
  TimeOut: 10
  ReadBufferSize: 4096

Log:
  ServiceName: msggateway-ws
  Level: info


Prometheus:
  Host: 0.0.0.0
  Port: 81
  Path: /metrics

Telemetry:
  Name: msggateway-ws
  Endpoint: http://192.168.1.98:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

#rpc service
ImUserRpc:
  Endpoints:
    - 192.168.1.98:10011

MsgRpc:
  Endpoints:
    - 192.168.1.98:10012

SendMsgRateLimit:
  Enable: true
  Seconds: 1
  Quota: 3

Redis:
  Host: 192.168.1.98:6379
  Pass: "123456"
  Type: node
RpcPort: 8080