Name: msgtransfer-history-cassandra

Log:
  ServiceName: msgtransfer-history-cassandra
  Level: info

Prometheus:
  Host: 0.0.0.0
  Port: 8080
  Path: /metrics

Telemetry:
  Name: msgtransfer-history-cassandra
  Endpoint: http://192.168.1.98:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger
Kafka:
  StorageConsumer:
    Brokers:
      - 192.168.1.98:9092
    Topic: im_msg
    MsgToHistoryGroupID: msgtransfer_history
  SinglePush:
    Brokers:
      - 192.168.1.98:9092
    Topic: im_msg_push_single
  GroupPush:
    Brokers:
      - 192.168.1.98:9092
    Topic: im_msg_push_group

Redis:
  Conf:
    Host: 192.168.1.98:6379
    Pass: "123456"
    Type: node
  DB: 0

Cassandra:
  Hosts:
    - 192.168.1.98
  Port: 9042
  Keyspace: "pathim"
  Username: "cassandra"
  Password: "cassandra"
  Consistency: ONE
  SingleChatMsgTableName: "single_chat_msg"
  GroupChatMsgTableName: "group_chat_msg"
  TimeoutSecond: 5

MsgPushRpc:
  Endpoints:
    - msgpush-rpc:8080
ImUserRpc:
  Endpoints:
    - imuser-rpc:8080