---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-imuser-rpc
  namespace: pathim
data:
  imuser.yaml: |-
    Name: imuser-rpc
    ListenOn: :8080
    Log:
      ServiceName: imuser-rpc
      Level: info
    Prometheus:
      Host: 0.0.0.0
      Port: 80
      Path: /metrics
    Telemetry:
      Name: imuser-rpc
      Endpoint: http://101.43.214.203:14268/api/traces
      Sampler: 1.0
      Batcher: jaeger
    Mysql:
      Addr: "root:123456@tcp(10.0.12.6:3306)/oicq?charset=utf8mb4&parseTime=True&loc=Local&timeout=20s&readTimeout=20s&writeTimeout=20s"
      LogLevel: info
      MaxIdleConns: 10
      MaxOpenConns: 10