// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: im-user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecvMsgOpt int32

const (
	RecvMsgOpt_ReceiveMessage          RecvMsgOpt = 0
	RecvMsgOpt_NotReceiveMessage       RecvMsgOpt = 1
	RecvMsgOpt_ReceiveNotNotifyMessage RecvMsgOpt = 2
)

// Enum value maps for RecvMsgOpt.
var (
	RecvMsgOpt_name = map[int32]string{
		0: "ReceiveMessage",
		1: "NotReceiveMessage",
		2: "ReceiveNotNotifyMessage",
	}
	RecvMsgOpt_value = map[string]int32{
		"ReceiveMessage":          0,
		"NotReceiveMessage":       1,
		"ReceiveNotNotifyMessage": 2,
	}
)

func (x RecvMsgOpt) Enum() *RecvMsgOpt {
	p := new(RecvMsgOpt)
	*p = x
	return p
}

func (x RecvMsgOpt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecvMsgOpt) Descriptor() protoreflect.EnumDescriptor {
	return file_im_user_proto_enumTypes[0].Descriptor()
}

func (RecvMsgOpt) Type() protoreflect.EnumType {
	return &file_im_user_proto_enumTypes[0]
}

func (x RecvMsgOpt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecvMsgOpt.Descriptor instead.
func (RecvMsgOpt) EnumDescriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{0}
}

type UserCallbackReq_Event int32

const (
	UserCallbackReq_Online      UserCallbackReq_Event = 0
	UserCallbackReq_Offline     UserCallbackReq_Event = 1
	UserCallbackReq_MsgTooOften UserCallbackReq_Event = 2
)

// Enum value maps for UserCallbackReq_Event.
var (
	UserCallbackReq_Event_name = map[int32]string{
		0: "Online",
		1: "Offline",
		2: "MsgTooOften",
	}
	UserCallbackReq_Event_value = map[string]int32{
		"Online":      0,
		"Offline":     1,
		"MsgTooOften": 2,
	}
)

func (x UserCallbackReq_Event) Enum() *UserCallbackReq_Event {
	p := new(UserCallbackReq_Event)
	*p = x
	return p
}

func (x UserCallbackReq_Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserCallbackReq_Event) Descriptor() protoreflect.EnumDescriptor {
	return file_im_user_proto_enumTypes[1].Descriptor()
}

func (UserCallbackReq_Event) Type() protoreflect.EnumType {
	return &file_im_user_proto_enumTypes[1]
}

func (x UserCallbackReq_Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserCallbackReq_Event.Descriptor instead.
func (UserCallbackReq_Event) EnumDescriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{17, 0}
}

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommonResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID         string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Nickname       string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FaceURL        string `protobuf:"bytes,3,opt,name=faceURL,proto3" json:"faceURL,omitempty"`
	Gender         int32  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber    string `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Birth          uint32 `protobuf:"varint,6,opt,name=birth,proto3" json:"birth,omitempty"`
	Email          string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Ex             string `protobuf:"bytes,8,opt,name=ex,proto3" json:"ex,omitempty"`
	CreateTime     uint32 `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	AppMangerLevel int32  `protobuf:"varint,10,opt,name=appMangerLevel,proto3" json:"appMangerLevel,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserInfo) GetBirth() uint32 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *UserInfo) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserInfo) GetAppMangerLevel() int32 {
	if x != nil {
		return x.AppMangerLevel
	}
	return 0
}

type GetGroupMemberIDListFromCacheReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID string `protobuf:"bytes,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *GetGroupMemberIDListFromCacheReq) Reset() {
	*x = GetGroupMemberIDListFromCacheReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupMemberIDListFromCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberIDListFromCacheReq) ProtoMessage() {}

func (x *GetGroupMemberIDListFromCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberIDListFromCacheReq.ProtoReflect.Descriptor instead.
func (*GetGroupMemberIDListFromCacheReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupMemberIDListFromCacheReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type GetGroupMemberIDListFromCacheResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp   *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	MemberIDList []string    `protobuf:"bytes,2,rep,name=memberIDList,proto3" json:"memberIDList,omitempty"`
}

func (x *GetGroupMemberIDListFromCacheResp) Reset() {
	*x = GetGroupMemberIDListFromCacheResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupMemberIDListFromCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberIDListFromCacheResp) ProtoMessage() {}

func (x *GetGroupMemberIDListFromCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberIDListFromCacheResp.ProtoReflect.Descriptor instead.
func (*GetGroupMemberIDListFromCacheResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupMemberIDListFromCacheResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *GetGroupMemberIDListFromCacheResp) GetMemberIDList() []string {
	if x != nil {
		return x.MemberIDList
	}
	return nil
}

type IfAInBBlacklistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AUserID string `protobuf:"bytes,1,opt,name=aUserID,proto3" json:"aUserID,omitempty"`
	BUserID string `protobuf:"bytes,2,opt,name=bUserID,proto3" json:"bUserID,omitempty"`
}

func (x *IfAInBBlacklistReq) Reset() {
	*x = IfAInBBlacklistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBBlacklistReq) ProtoMessage() {}

func (x *IfAInBBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBBlacklistReq.ProtoReflect.Descriptor instead.
func (*IfAInBBlacklistReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{4}
}

func (x *IfAInBBlacklistReq) GetAUserID() string {
	if x != nil {
		return x.AUserID
	}
	return ""
}

func (x *IfAInBBlacklistReq) GetBUserID() string {
	if x != nil {
		return x.BUserID
	}
	return ""
}

type IfAInBBlacklistResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp    *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	IsInBlacklist bool        `protobuf:"varint,2,opt,name=isInBlacklist,proto3" json:"isInBlacklist,omitempty"`
}

func (x *IfAInBBlacklistResp) Reset() {
	*x = IfAInBBlacklistResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBBlacklistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBBlacklistResp) ProtoMessage() {}

func (x *IfAInBBlacklistResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBBlacklistResp.ProtoReflect.Descriptor instead.
func (*IfAInBBlacklistResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{5}
}

func (x *IfAInBBlacklistResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *IfAInBBlacklistResp) GetIsInBlacklist() bool {
	if x != nil {
		return x.IsInBlacklist
	}
	return false
}

type IfAInBFriendListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AUserID string `protobuf:"bytes,1,opt,name=aUserID,proto3" json:"aUserID,omitempty"`
	BUserID string `protobuf:"bytes,2,opt,name=bUserID,proto3" json:"bUserID,omitempty"`
}

func (x *IfAInBFriendListReq) Reset() {
	*x = IfAInBFriendListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBFriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBFriendListReq) ProtoMessage() {}

func (x *IfAInBFriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBFriendListReq.ProtoReflect.Descriptor instead.
func (*IfAInBFriendListReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{6}
}

func (x *IfAInBFriendListReq) GetAUserID() string {
	if x != nil {
		return x.AUserID
	}
	return ""
}

func (x *IfAInBFriendListReq) GetBUserID() string {
	if x != nil {
		return x.BUserID
	}
	return ""
}

type IfAInBFriendListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp     *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	IsInFriendList bool        `protobuf:"varint,2,opt,name=isInFriendList,proto3" json:"isInFriendList,omitempty"`
}

func (x *IfAInBFriendListResp) Reset() {
	*x = IfAInBFriendListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfAInBFriendListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfAInBFriendListResp) ProtoMessage() {}

func (x *IfAInBFriendListResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfAInBFriendListResp.ProtoReflect.Descriptor instead.
func (*IfAInBFriendListResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{7}
}

func (x *IfAInBFriendListResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *IfAInBFriendListResp) GetIsInFriendList() bool {
	if x != nil {
		return x.IsInFriendList
	}
	return false
}

type GetSingleConversationRecvMsgOptsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SenderUserID string `protobuf:"bytes,2,opt,name=senderUserID,proto3" json:"senderUserID,omitempty"`
}

func (x *GetSingleConversationRecvMsgOptsReq) Reset() {
	*x = GetSingleConversationRecvMsgOptsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleConversationRecvMsgOptsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleConversationRecvMsgOptsReq) ProtoMessage() {}

func (x *GetSingleConversationRecvMsgOptsReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleConversationRecvMsgOptsReq.ProtoReflect.Descriptor instead.
func (*GetSingleConversationRecvMsgOptsReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetSingleConversationRecvMsgOptsReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetSingleConversationRecvMsgOptsReq) GetSenderUserID() string {
	if x != nil {
		return x.SenderUserID
	}
	return ""
}

type GetSingleConversationRecvMsgOptsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	Opts       RecvMsgOpt  `protobuf:"varint,2,opt,name=opts,proto3,enum=imuser.RecvMsgOpt" json:"opts,omitempty"`
}

func (x *GetSingleConversationRecvMsgOptsResp) Reset() {
	*x = GetSingleConversationRecvMsgOptsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleConversationRecvMsgOptsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleConversationRecvMsgOptsResp) ProtoMessage() {}

func (x *GetSingleConversationRecvMsgOptsResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleConversationRecvMsgOptsResp.ProtoReflect.Descriptor instead.
func (*GetSingleConversationRecvMsgOptsResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetSingleConversationRecvMsgOptsResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *GetSingleConversationRecvMsgOptsResp) GetOpts() RecvMsgOpt {
	if x != nil {
		return x.Opts
	}
	return RecvMsgOpt_ReceiveMessage
}

type GetUserListFromGroupWithOptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID    string       `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Opts       []RecvMsgOpt `protobuf:"varint,2,rep,packed,name=opts,proto3,enum=imuser.RecvMsgOpt" json:"opts,omitempty"`
	UserIDList []string     `protobuf:"bytes,3,rep,name=userIDList,proto3" json:"userIDList,omitempty"`
}

func (x *GetUserListFromGroupWithOptReq) Reset() {
	*x = GetUserListFromGroupWithOptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserListFromGroupWithOptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListFromGroupWithOptReq) ProtoMessage() {}

func (x *GetUserListFromGroupWithOptReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListFromGroupWithOptReq.ProtoReflect.Descriptor instead.
func (*GetUserListFromGroupWithOptReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserListFromGroupWithOptReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GetUserListFromGroupWithOptReq) GetOpts() []RecvMsgOpt {
	if x != nil {
		return x.Opts
	}
	return nil
}

func (x *GetUserListFromGroupWithOptReq) GetUserIDList() []string {
	if x != nil {
		return x.UserIDList
	}
	return nil
}

type UserIDOpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string     `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Opts   RecvMsgOpt `protobuf:"varint,2,opt,name=opts,proto3,enum=imuser.RecvMsgOpt" json:"opts,omitempty"`
}

func (x *UserIDOpt) Reset() {
	*x = UserIDOpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDOpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDOpt) ProtoMessage() {}

func (x *UserIDOpt) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDOpt.ProtoReflect.Descriptor instead.
func (*UserIDOpt) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserIDOpt) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserIDOpt) GetOpts() RecvMsgOpt {
	if x != nil {
		return x.Opts
	}
	return RecvMsgOpt_ReceiveMessage
}

type GetUserListFromGroupWithOptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp    *CommonResp  `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	UserIDOptList []*UserIDOpt `protobuf:"bytes,2,rep,name=UserIDOptList,proto3" json:"UserIDOptList,omitempty"`
}

func (x *GetUserListFromGroupWithOptResp) Reset() {
	*x = GetUserListFromGroupWithOptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserListFromGroupWithOptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListFromGroupWithOptResp) ProtoMessage() {}

func (x *GetUserListFromGroupWithOptResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListFromGroupWithOptResp.ProtoReflect.Descriptor instead.
func (*GetUserListFromGroupWithOptResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserListFromGroupWithOptResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *GetUserListFromGroupWithOptResp) GetUserIDOptList() []*UserIDOpt {
	if x != nil {
		return x.UserIDOptList
	}
	return nil
}

type VerifyTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	SendID   string `protobuf:"bytes,3,opt,name=sendID,proto3" json:"sendID,omitempty"`
}

func (x *VerifyTokenReq) Reset() {
	*x = VerifyTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenReq) ProtoMessage() {}

func (x *VerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyTokenReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *VerifyTokenReq) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

type VerifyTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg  string `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *VerifyTokenResp) Reset() {
	*x = VerifyTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResp) ProtoMessage() {}

func (x *VerifyTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResp.ProtoReflect.Descriptor instead.
func (*VerifyTokenResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyTokenResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VerifyTokenResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyTokenResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type IfPreviewMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderID   string `protobuf:"bytes,1,opt,name=senderID,proto3" json:"senderID,omitempty"`
	ReceiverID string `protobuf:"bytes,2,opt,name=receiverID,proto3" json:"receiverID,omitempty"`
	GroupID    string `protobuf:"bytes,3,opt,name=groupID,proto3" json:"groupID,omitempty"`
}

func (x *IfPreviewMessageReq) Reset() {
	*x = IfPreviewMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfPreviewMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfPreviewMessageReq) ProtoMessage() {}

func (x *IfPreviewMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfPreviewMessageReq.ProtoReflect.Descriptor instead.
func (*IfPreviewMessageReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{15}
}

func (x *IfPreviewMessageReq) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

func (x *IfPreviewMessageReq) GetReceiverID() string {
	if x != nil {
		return x.ReceiverID
	}
	return ""
}

func (x *IfPreviewMessageReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type IfPreviewMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp   *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	IfPreview    bool        `protobuf:"varint,2,opt,name=ifPreview,proto3" json:"ifPreview,omitempty"`
	ReplaceTitle string      `protobuf:"bytes,3,opt,name=replaceTitle,proto3" json:"replaceTitle,omitempty"`
}

func (x *IfPreviewMessageResp) Reset() {
	*x = IfPreviewMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfPreviewMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfPreviewMessageResp) ProtoMessage() {}

func (x *IfPreviewMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfPreviewMessageResp.ProtoReflect.Descriptor instead.
func (*IfPreviewMessageResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{16}
}

func (x *IfPreviewMessageResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *IfPreviewMessageResp) GetIfPreview() bool {
	if x != nil {
		return x.IfPreview
	}
	return false
}

func (x *IfPreviewMessageResp) GetReplaceTitle() string {
	if x != nil {
		return x.ReplaceTitle
	}
	return ""
}

type UserCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event UserCallbackReq_Event `protobuf:"varint,1,opt,name=event,proto3,enum=imuser.UserCallbackReq_Event" json:"event,omitempty"`
	// 13位时间戳
	Timestamp  int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserID     string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Platform   string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	RemoteAddr string `protobuf:"bytes,5,opt,name=RemoteAddr,proto3" json:"RemoteAddr,omitempty"`
}

func (x *UserCallbackReq) Reset() {
	*x = UserCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCallbackReq) ProtoMessage() {}

func (x *UserCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCallbackReq.ProtoReflect.Descriptor instead.
func (*UserCallbackReq) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{17}
}

func (x *UserCallbackReq) GetEvent() UserCallbackReq_Event {
	if x != nil {
		return x.Event
	}
	return UserCallbackReq_Online
}

func (x *UserCallbackReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UserCallbackReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserCallbackReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UserCallbackReq) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type UserCallbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserCallbackResp) Reset() {
	*x = UserCallbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_user_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCallbackResp) ProtoMessage() {}

func (x *UserCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_user_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCallbackResp.ProtoReflect.Descriptor instead.
func (*UserCallbackResp) Descriptor() ([]byte, []int) {
	return file_im_user_proto_rawDescGZIP(), []int{18}
}

var File_im_user_proto protoreflect.FileDescriptor

var file_im_user_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6d, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x96, 0x02, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x65,
	0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63, 0x65, 0x55,
	0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x78, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x4d,
	0x61, 0x6e, 0x67, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x61, 0x70, 0x70, 0x4d, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0x3c, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x7b,
	0x0a, 0x21, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x12, 0x49,
	0x66, 0x41, 0x49, 0x6e, 0x42, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x6f, 0x0a, 0x13, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x24, 0x0a, 0x0d, 0x69, 0x73, 0x49, 0x6e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x49, 0x6e, 0x42, 0x6c, 0x61,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x13, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x72, 0x0a, 0x14, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a,
	0x0e, 0x69, 0x73, 0x49, 0x6e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x49, 0x6e, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x82, 0x01, 0x0a, 0x24, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x63,
	0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x82, 0x01,
	0x0a, 0x1e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x04, 0x6f, 0x70,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x52, 0x04, 0x6f, 0x70,
	0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x4b, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x4f, 0x70, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22,
	0x8e, 0x01, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x4f, 0x70, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x4f, 0x70,
	0x74, 0x52, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x4f, 0x70, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x5a, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x22, 0x55, 0x0a, 0x0f,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x6b, 0x0a, 0x13, 0x49, 0x66, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44,
	0x22, 0x8c, 0x01, 0x0a, 0x14, 0x49, 0x66, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x66, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x66, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x22, 0x0a, 0x0c, 0x72,
	0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22,
	0xeb, 0x01, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22, 0x31, 0x0a, 0x05, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x4d, 0x73, 0x67, 0x54, 0x6f, 0x6f, 0x4f, 0x66, 0x74, 0x65, 0x6e, 0x10, 0x02, 0x22, 0x12, 0x0a,
	0x10, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x2a, 0x54, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x12,
	0x12, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x02, 0x32, 0xeb, 0x04, 0x0a, 0x0d, 0x69, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x49, 0x66, 0x41,
	0x49, 0x6e, 0x42, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x69,
	0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x10, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x69, 0x6d, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x49, 0x66, 0x41, 0x49, 0x6e, 0x42, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x7d, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63,
	0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x2b, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x6e, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4f,
	0x70, 0x74, 0x12, 0x26, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x69, 0x6d, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x69, 0x6d, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x10, 0x49, 0x66, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x49, 0x66, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x66,
	0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x41, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x12, 0x17, 0x2e, 0x69, 0x6d, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x69, 0x6d,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_im_user_proto_rawDescOnce sync.Once
	file_im_user_proto_rawDescData = file_im_user_proto_rawDesc
)

func file_im_user_proto_rawDescGZIP() []byte {
	file_im_user_proto_rawDescOnce.Do(func() {
		file_im_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_user_proto_rawDescData)
	})
	return file_im_user_proto_rawDescData
}

var file_im_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_im_user_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_im_user_proto_goTypes = []interface{}{
	(RecvMsgOpt)(0),                              // 0: imuser.RecvMsgOpt
	(UserCallbackReq_Event)(0),                   // 1: imuser.UserCallbackReq.Event
	(*CommonResp)(nil),                           // 2: imuser.CommonResp
	(*UserInfo)(nil),                             // 3: imuser.UserInfo
	(*GetGroupMemberIDListFromCacheReq)(nil),     // 4: imuser.GetGroupMemberIDListFromCacheReq
	(*GetGroupMemberIDListFromCacheResp)(nil),    // 5: imuser.GetGroupMemberIDListFromCacheResp
	(*IfAInBBlacklistReq)(nil),                   // 6: imuser.IfAInBBlacklistReq
	(*IfAInBBlacklistResp)(nil),                  // 7: imuser.IfAInBBlacklistResp
	(*IfAInBFriendListReq)(nil),                  // 8: imuser.IfAInBFriendListReq
	(*IfAInBFriendListResp)(nil),                 // 9: imuser.IfAInBFriendListResp
	(*GetSingleConversationRecvMsgOptsReq)(nil),  // 10: imuser.GetSingleConversationRecvMsgOptsReq
	(*GetSingleConversationRecvMsgOptsResp)(nil), // 11: imuser.GetSingleConversationRecvMsgOptsResp
	(*GetUserListFromGroupWithOptReq)(nil),       // 12: imuser.GetUserListFromGroupWithOptReq
	(*UserIDOpt)(nil),                            // 13: imuser.UserIDOpt
	(*GetUserListFromGroupWithOptResp)(nil),      // 14: imuser.GetUserListFromGroupWithOptResp
	(*VerifyTokenReq)(nil),                       // 15: imuser.VerifyTokenReq
	(*VerifyTokenResp)(nil),                      // 16: imuser.VerifyTokenResp
	(*IfPreviewMessageReq)(nil),                  // 17: imuser.IfPreviewMessageReq
	(*IfPreviewMessageResp)(nil),                 // 18: imuser.IfPreviewMessageResp
	(*UserCallbackReq)(nil),                      // 19: imuser.UserCallbackReq
	(*UserCallbackResp)(nil),                     // 20: imuser.UserCallbackResp
}
var file_im_user_proto_depIdxs = []int32{
	2,  // 0: imuser.GetGroupMemberIDListFromCacheResp.commonResp:type_name -> imuser.CommonResp
	2,  // 1: imuser.IfAInBBlacklistResp.commonResp:type_name -> imuser.CommonResp
	2,  // 2: imuser.IfAInBFriendListResp.commonResp:type_name -> imuser.CommonResp
	2,  // 3: imuser.GetSingleConversationRecvMsgOptsResp.commonResp:type_name -> imuser.CommonResp
	0,  // 4: imuser.GetSingleConversationRecvMsgOptsResp.opts:type_name -> imuser.RecvMsgOpt
	0,  // 5: imuser.GetUserListFromGroupWithOptReq.opts:type_name -> imuser.RecvMsgOpt
	0,  // 6: imuser.UserIDOpt.opts:type_name -> imuser.RecvMsgOpt
	2,  // 7: imuser.GetUserListFromGroupWithOptResp.commonResp:type_name -> imuser.CommonResp
	13, // 8: imuser.GetUserListFromGroupWithOptResp.UserIDOptList:type_name -> imuser.UserIDOpt
	2,  // 9: imuser.IfPreviewMessageResp.commonResp:type_name -> imuser.CommonResp
	1,  // 10: imuser.UserCallbackReq.event:type_name -> imuser.UserCallbackReq.Event
	6,  // 11: imuser.imUserService.IfAInBBlacklist:input_type -> imuser.IfAInBBlacklistReq
	8,  // 12: imuser.imUserService.IfAInBFriendList:input_type -> imuser.IfAInBFriendListReq
	10, // 13: imuser.imUserService.GetSingleConversationRecvMsgOpts:input_type -> imuser.GetSingleConversationRecvMsgOptsReq
	12, // 14: imuser.imUserService.GetUserListFromGroupWithOpt:input_type -> imuser.GetUserListFromGroupWithOptReq
	15, // 15: imuser.imUserService.VerifyToken:input_type -> imuser.VerifyTokenReq
	17, // 16: imuser.imUserService.IfPreviewMessage:input_type -> imuser.IfPreviewMessageReq
	19, // 17: imuser.imUserService.UserCallback:input_type -> imuser.UserCallbackReq
	7,  // 18: imuser.imUserService.IfAInBBlacklist:output_type -> imuser.IfAInBBlacklistResp
	9,  // 19: imuser.imUserService.IfAInBFriendList:output_type -> imuser.IfAInBFriendListResp
	11, // 20: imuser.imUserService.GetSingleConversationRecvMsgOpts:output_type -> imuser.GetSingleConversationRecvMsgOptsResp
	14, // 21: imuser.imUserService.GetUserListFromGroupWithOpt:output_type -> imuser.GetUserListFromGroupWithOptResp
	16, // 22: imuser.imUserService.VerifyToken:output_type -> imuser.VerifyTokenResp
	18, // 23: imuser.imUserService.IfPreviewMessage:output_type -> imuser.IfPreviewMessageResp
	20, // 24: imuser.imUserService.UserCallback:output_type -> imuser.UserCallbackResp
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_im_user_proto_init() }
func file_im_user_proto_init() {
	if File_im_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_im_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupMemberIDListFromCacheReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupMemberIDListFromCacheResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBBlacklistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBBlacklistResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBFriendListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfAInBFriendListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleConversationRecvMsgOptsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleConversationRecvMsgOptsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserListFromGroupWithOptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIDOpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserListFromGroupWithOptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfPreviewMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfPreviewMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_user_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCallbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_user_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_user_proto_goTypes,
		DependencyIndexes: file_im_user_proto_depIdxs,
		EnumInfos:         file_im_user_proto_enumTypes,
		MessageInfos:      file_im_user_proto_msgTypes,
	}.Build()
	File_im_user_proto = out.File
	file_im_user_proto_rawDesc = nil
	file_im_user_proto_goTypes = nil
	file_im_user_proto_depIdxs = nil
}
