// Code generated by goctl. DO NOT EDIT!
// Source: group.proto

package server

import (
	"context"

	"github.com/showurl/Path-IM-Server-OICQ/app/group/rpc/internal/logic"
	"github.com/showurl/Path-IM-Server-OICQ/app/group/rpc/internal/svc"
	"github.com/showurl/Path-IM-Server-OICQ/app/group/rpc/pb"
)

type GroupServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGroupServiceServer
}

func NewGroupServiceServer(svcCtx *svc.ServiceContext) *GroupServiceServer {
	return &GroupServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServiceServer) CreateGroup(ctx context.Context, in *pb.CreateGroupReq) (*pb.CreateGroupResp, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupServiceServer) GetGroup(ctx context.Context, in *pb.GetGroupReq) (*pb.GetGroupResp, error) {
	l := logic.NewGetGroupLogic(ctx, s.svcCtx)
	return l.GetGroup(in)
}

func (s *GroupServiceServer) UpdateGroup(ctx context.Context, in *pb.UpdateGroupReq) (*pb.UpdateGroupResp, error) {
	l := logic.NewUpdateGroupLogic(ctx, s.svcCtx)
	return l.UpdateGroup(in)
}

func (s *GroupServiceServer) DeleteGroup(ctx context.Context, in *pb.DeleteGroupReq) (*pb.DeleteGroupResp, error) {
	l := logic.NewDeleteGroupLogic(ctx, s.svcCtx)
	return l.DeleteGroup(in)
}

func (s *GroupServiceServer) GetGroupMember(ctx context.Context, in *pb.GetGroupMemberReq) (*pb.GetGroupMemberResp, error) {
	l := logic.NewGetGroupMemberLogic(ctx, s.svcCtx)
	return l.GetGroupMember(in)
}

func (s *GroupServiceServer) GetGroupIds(ctx context.Context, in *pb.GetGroupIdsReq) (*pb.GetGroupIdsResp, error) {
	l := logic.NewGetGroupIdsLogic(ctx, s.svcCtx)
	return l.GetGroupIds(in)
}

func (s *GroupServiceServer) AddGroupMember(ctx context.Context, in *pb.AddGroupMemberReq) (*pb.AddGroupMemberResp, error) {
	l := logic.NewAddGroupMemberLogic(ctx, s.svcCtx)
	return l.AddGroupMember(in)
}

func (s *GroupServiceServer) DeleteGroupMember(ctx context.Context, in *pb.DeleteGroupMemberReq) (*pb.DeleteGroupMemberResp, error) {
	l := logic.NewDeleteGroupMemberLogic(ctx, s.svcCtx)
	return l.DeleteGroupMember(in)
}

func (s *GroupServiceServer) GetGroupMemberModel(ctx context.Context, in *pb.GetGroupMemberModelReq) (*pb.GetGroupMemberModelResp, error) {
	l := logic.NewGetGroupMemberModelLogic(ctx, s.svcCtx)
	return l.GetGroupMemberModel(in)
}
