// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/showurl/Path-IM-Server-OICQ/app/user/rpc/internal/logic"
	"github.com/showurl/Path-IM-Server-OICQ/app/user/rpc/internal/svc"
	"github.com/showurl/Path-IM-Server-OICQ/app/user/rpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) GetToken(ctx context.Context, in *pb.GetTokenReq) (*pb.GetTokenResp, error) {
	l := logic.NewGetTokenLogic(ctx, s.svcCtx)
	return l.GetToken(in)
}

func (s *UserServiceServer) GetUserByUsername(ctx context.Context, in *pb.GetUserByUsernameReq) (*pb.GetUserByUsernameResp, error) {
	l := logic.NewGetUserByUsernameLogic(ctx, s.svcCtx)
	return l.GetUserByUsername(in)
}

func (s *UserServiceServer) GetUserByIds(ctx context.Context, in *pb.GetUserByIdsReq) (*pb.GetUserByIdsResp, error) {
	l := logic.NewGetUserByIdsLogic(ctx, s.svcCtx)
	return l.GetUserByIds(in)
}

func (s *UserServiceServer) UpdateUser(ctx context.Context, in *pb.UpdateUserReq) (*pb.UpdateUserResp, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServiceServer) GetUserConfig(ctx context.Context, in *pb.GetUserConfigReq) (*pb.GetUserConfigResp, error) {
	l := logic.NewGetUserConfigLogic(ctx, s.svcCtx)
	return l.GetUserConfig(in)
}

func (s *UserServiceServer) UpdateUserConfig(ctx context.Context, in *pb.UpdateUserConfigReq) (*pb.UpdateUserConfigResp, error) {
	l := logic.NewUpdateUserConfigLogic(ctx, s.svcCtx)
	return l.UpdateUserConfig(in)
}
