// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	imuser "github.com/showurl/Path-IM-Server-OICQ/app/api/internal/handler/imuser"
	"github.com/showurl/Path-IM-Server-OICQ/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/white/login",
				Handler: imuser.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
